### ISSUE TITLE
Non daily schedule issue

### ISSUE THREAD

**Issue by jwaddilove** [carekit-apple/CareKit#279] opened 2019-06-21 13:59 UTC
Environment iOS 13 Beta 2 (iPad & iPhone)
CareKit V2 Beta: commit 96880a9
Locale: UK

I am having problems with schudules that are less frequent that daily.

To illusrate the problem make the following change to OCKSample AppDelegate:

Where the doxylamine schedule is initialised with two `OCKScheduleElement` calls, remove the `beforeBreakfast`  schedule. I would expect the result to only show a Card on alternate days.

If you look at the screen shots correct.png shows the days where a dose is require. However, on the alternate day (see incorrect.png) a blank card appears. I would expect the card to be committed?!

Again, thank you for any help...  Jonathan

![correct](https://user-images.githubusercontent.com/16636085/59927650-e2746580-9434-11e9-93ca-c605829ddbeb.PNG)
![incorrect](https://user-images.githubusercontent.com/16636085/59927653-e2746580-9434-11e9-9a69-88f17fb038b2.PNG)

**Comment by erik-apple** [comment] 2019-06-21 16:16
Hi Jonathon, what you've discovered is actually the intended behavior! I wanted to cover this more in the WWDC demo, but there wasn't enough time to go into detail. I'll try to explain it here, and give you some hints about how to get the behaviour you want!

The task as defined in the app delegate starts a few days ago and has no end date. That is, the task exists on all days, even though there will only be events for that task every other day. So what is happening, is that when you run the query for tasks, it is correctly returning to you the 2 tasks exist on the day you've specified. You then use those tasks to create cards, and the cards attempt to populate themselves with events for those tasks, but as you've noticed, there are no events on some days, so the cards remain empty.

To get the behaviour you want, the solution is to query for **events** instead of just tasks, and then display cards only if there are more 0 events.

Take a look at the `store.fetchEvents` method, that's the one probably want to be using! It's not quite as convenient right now because it can only fetch the events for a single task, but there's an update coming in the next couple of days that will make it more convenient.

We'll also be updating the sample app to make it behave the way you expect, as we think that's the true behavior that most developers are after.

**Comment by jwaddilove** [comment] 2019-06-21 16:35
Hi Erik, Thank you, I’ll refactor to query for events and also watch for the updates.

More general feedback:

1. As you move towards the September stable release are you planning to show (in the sample app?) any integration with HealthKit and/or ResearchKit?

2. One of my next goals is to make it easy to modify a care plan. My current thought is to use Swift Codeable to serialise OCKTask items to json and then email the user the amendments and add UTI (Filetype) support to my app. I understand the issues about security of sending clear text json.

3. Thinking of busy care teams it seems that an easy way to build and edit Tasks, etc would be to have an assistant app that has a UI that simplifies the creation of Tasks generating plist/json/etc that can be used by the bridge or email. I’m thinking of bottom up small surgeries that will not have public facing servers (this is a UK based idea).

Thank you for you time and interest.  Jonathan

**Comment by erik-apple** [comment] 2019-06-21 18:20
We've very recently started using Github to collect input from the community about what features they'd like to see implemented in CareKit. We plan to use community feedback to help us prioritize the order in which new features are added, so if you'd like to see HealthKit integration soon than later, the best thing to do would be to open an issue with a proposal and get it into the system where others can upvote it.

This is a brand new initiative and there isn't aren't any instructions about it in the project README yet, but if you open an issue we'll triage it and get it into the pipeline.

ResearchKit integration is definitely possible, but it presently seems unlikely that we will include in the sample app because we don't want to introduce dependencies. We'd be happy to provide some sample code showing you how to do it though. Are there certain components of ResearchKit that you're interested in integrating?

We made all of the structs in CareKit conform to `Codable` specifically to support use cases like yours. CareKit does not provide any guarantees about security, so it is your responsibility as the developer to make sure that you meet the data security regulations in your country. CareKit can help you out once the data is on device though! You could also conform your server to `OCKStoreProtocol`, and then CareKit would automatically read from and persist data directly to your server instead of saving it locally to disk.

CareKit can support your third use case as well, thought it doesn’t presently have any view controllers that support creation or modifications of tasks. CareKit is intended to allow users to build those components out themselves though, and we hope that if you do create new view controllers that are generic enough to be useful to others, we hope you’ll consider contributing them back to CareKit so the community can leverage them!

**Comment by jwaddilove** [comment] 2019-06-22 19:28
Thank you. If I end up with code of sufficient quality I will share it.

I'm looking forward to following your success. J

**Comment by erik-apple** [comment] 2019-07-02 17:26
@jwaddilove We just merged a pull request that addresses this issue! Check out the changes to the sample app. The gist is that `OCKTaskQuery` now as an `excludeTasksWithNoEvents` flag that will give you the behavior that you want.

**Closed by erik-apple** 2019-07-02 17:26 UTC
