### ISSUE TITLE
Question about OCKOutcome, OCKOutcomeValue, OCKSchedule, and OCKScheduleEvent

### ISSUE THREAD

**Issue by cbaker6** [carekit-apple/CareKit#418] opened 2020-04-21 23:47 UTC
It seems that OCKOutcome, OCKOutcomeValue, OCKSchedule, and OCKScheduleEvent are setup slightly different from OCKPatient, OCKCarePlan, OCKTask, etc. For example: 

1. OCKOutcome cannot be initialized with with an `id` and OCKStore creates one on it's own that looks something like, `x-coredata://BC6D5810-5D8F-4E27-A74B-C33F32E19387/OCKCDTask/p22_7` which looks more like the `localDatabaseID`
2. OCKOutcome, OCKOutcomeValue, OCKSchedule, and OCKScheduleEvent doesn't have an `id` at all
3. OCKSchedule doesn't have a `remoteId` (I haven't needed this so far because I've only needed to sync OCKScheduleElement to the cloud)

To get around the issues above, I use `userInfo` to add UUID's for each. Are id's missing, or in the case of OCKOutcome having it's `id` used in a different way setup like this for a particular reason?

The reason I ask this because when syncing between local devices and cloud, if a local OCKStore entity doesn't have an `id` and it's `remoteId` isn't set, then I don't see a way to link the local and cloud entities

**Comment by erik-apple** [comment] 2020-04-22 16:42
All very good questions and observations!

We like to describe the entities in CareKit’s store using the terms “top level”, “versioned”, and “un-versioned”.

Top level entities are the ones that you can save into the store directly. The top level entities are OCKPatient, OCKCarePlan, OCKContact, OCKTask, and OCKOutcome. By contrast, OCKSchedule, OCKOutcomeValue, and OCKPostalAddress (to name a few) can only be inserted into the store by attaching them to a top level entity and saving that top level entity into the store.

Versioned entities are just that — entities that are stored as a linked list of versions.
The versioned entities are OCKPatient, OCKCarePlan, OCKContact, and OCKTask.

Un-versioned entities do not have a notion of versions. The most notable of these is OCKOutcome because it’s also a top level entity. The others (OCKSchedule, OCKOutcomeValue, OCKPostalAddress, etc.) are pretty boring. 

The versioned entities can all be initialized with an `id`. I think you understand the pattern pretty well already. The `id` is used to associate different versions of the same object.

Outcomes have an `id`, but it is a computed property, and it isn’t related to versioning. An outcome get its “identity” from the version of the task it belongs to and its index. For example “The outcome for the 3rd event of the task with version x-coredata://ABCD” uniquely specifies a particular outcome.

You mentioned something about syncing OCKSchedule and the lack of a remoteID. I would recommend denormalizing schedule onto task for synchronization purposes. You should be able to treat OCKTask as one entity for synchronization purposes. In the cloud you might need to have a dedicated table for schedule elements, but that should be an implementation detail. When you pull tasks down from the cloud, the server should denormalize the schedule back onto the task before sending it to the client.

We’ve had some discussions about removing some of the properties on OCKSchedule and OCKScheduleElement in future releases to enforce that they not be treated like top-level objects. Whether or not we actually decide to do that is up in the air and will depend on how many apps rely on those properties, but if you can, you’d do well to synchronize them as a part of task instead of independently. 

If you go the route of denormalizing everything else into top-level entities, then you should be able to unambiguously associate all entities on the device with those in the cloud.

**Comment by cbaker6** [comment] 2020-04-30 20:18
Posting as different comments since it's long...

@erik-apple thank you for your detailed response. I've made a framework public, [PareCareKit](https://github.com/netreconlab/ParseCareKit) that syncs an apps CareStore (I'll discuss what gets synced later) to a dedicated [parse-server](https://github.com/parse-community/parse-server). I provide some links to other projects that point devs in the direction of making Parse HIPAA compliant with MongoDB and Postgres. A minor issue with ParseCareKit is I couldn't think of a way to use SPM with it because parse-server is written in objective-c and has another objective-c dependency. I think it's possible for me to make a podspec for CareKit on my personal fork and just keep that inline with CareKit here, but wanted to make sure that's okay with you all. I don't think it's necessary for me to deploy on cocoapods site, but I would like your suggestion on this... 

For the most part, I think I got lucky as I fell into designing: “top level”, “versioned”, and “un-versioned” on accident because I was converting my research based app from CareKit 1.0 to 2.0 and wanted to understand the differences. So I spent a lot of time going through the new CareKit documentation. Your added descriptions have provided a lot of clarity. PareCareKit currently only keeps current state of entities in the CareStore (mainly because of the design of parse-server) and for my current use-cases, it's okay for different versions of entities to live locally on a device.

> Outcomes have an id, but it is a computed property, and it isn’t related to versioning. An outcome get its “identity” from the version of the task it belongs to and its index. For example “The outcome for the 3rd event of the task with version x-coredata://ABCD” uniquely specifies a particular outcome.

This makes since now. Based on your description and the documentation, I can see how this can work well when the CareStore operates on 1 device and is synced to the cloud, but what happens if a user has multiple devices (or they get a new device and the CareStore needs to be recreated from the Cloud)? Recreating `OCKOutcomes` will have an issue because you can't specify the `id` (the other top-level entities wouldn't have this issue). Note, that my thought process here may be limited to a design aspect of ParseCareKit I mentioned earlier, "PareCareKit currently only keeps current state of entities in the CareStore". I guess if the the cloud contained all versioned data, if you are syncing a new CareStore from the Cloud, it should compute the same `id` for an `OCKOutcome`, assuming the versions were created in the exact same order, and the `id` purely uses the `task id` and it's `index` and doesn't use anything related to time/date, etc?  To keep entities in-sync, I keep a 1-to-1 mapping of `id (OCK) <-> uuid (ParseCareKit)` and `remoteID (OCK) <-> objectId (ParseCareKit)`. To get around the syncing issue of `OCKOutcome`, I simply add a generated `uuid` to `userInfo`.

**Comment by cbaker6** [comment] 2020-04-30 20:18
> You mentioned something about syncing OCKSchedule and the lack of a remoteID. I would recommend denormalizing schedule onto task for synchronization purposes. You should be able to treat OCKTask as one entity for synchronization purposes. In the cloud you might need to have a dedicated table for schedule elements, but that should be an implementation detail. When you pull tasks down from the cloud, the server should denormalize the schedule back onto the task before sending it to the client.

This is another place I got lucky. When designing, I didn't see a need to sync OCKSchedule to the cloud, but was unsure why it didn't have a remoteId. I did exactly what you mentioned and keep a table of [ScheduleElement](https://github.com/netreconlab/ParseCareKit/blob/master/ParseCareKit/ScheduleElement.swift)'s in the cloud to recreate schedules locally.

**Comment by cbaker6** [comment] 2020-04-30 20:19
> We’ve had some discussions about removing some of the properties on OCKSchedule and OCKScheduleElement in future releases to enforce that they not be treated like top-level objects. Whether or not we actually decide to do that is up in the air and will depend on how many apps rely on those properties, but if you can, you’d do well to synchronize them as a part of task instead of independently. If you go the route of denormalizing everything else into top-level entities, then you should be able to unambiguously associate all entities on the device with those in the cloud.

I'll use this to point out some things I've noticed with `OCKScheduleElement` and `OCKOutcomeValue`. I've added `id`'s to each of these in `userInfo`, mainly I'll explain why below (I'll focus mainly on `OCKOutcomeValue`). It seems that CareKit's initial design is for measuring and helping with patient adherence. In these types of situations (from my understanding anyways) patients are prescribed to do something (or take medications) a certain amount of times and log it's completion. In these cases, typically 1 `OCKOutcomeValue` is associated with 1 `OCKOutcome` completes an event and is associated with a task, scheduleElement... It seems that if a patient is suppose to complete 3 events in 1 day, but they end up completing 5 (3 of them by the specified times, 2 later) instead of creating more events (there's no more to be created), these additional `OCKOutcome`s essentially become 2 `OCKOutcomeValue`'s and are appended to the third `OCKOutcome` in which this third `OCKOutcome` now has an array of 3 `OCKOutcomeValue`s, is this correct? If so, when a delete/update occurs this third `OCKOutcome`, `notification.category == .update` is called no matter if you are deleting a specific `OCKOutcomeValue` or updating it (I haven't tested this yet, this is a guess). When syncing to the cloud, how would we know what specific `OCKOutcomeValue` has been changed without an `id` on each? If they have `id`s, in the case of deletes, can simply do an `intersection` of `id`s to determine what `OCKOutcomeValue` to remove from the Cloud; with update, we just check difference of the date.

Related to my last point is storing HealthKit data in CareStore which wasn't too hard to setup. Here, I have a design question because of the "patient adherence" of `OCKOutcome` and `OCKOutcomeValue`, for most HealthKit samples, like "steps", the amount of samples that occur a day are arbitrary, so I couldn't think of a reasonable way to set events. Instead, I create 1 event for each sample type, and append each sample/OCKOutcomeValue to the value of `OCKOutcome`. Is this a good approach to this problem? If so, if my point about updates/deletes on `OCKOutcomeValue`s are also true, then how do you suggest managing `values` with out an `id`

**Comment by cbaker6** [comment] 2020-04-30 20:33
Lastly, the CareKit entities I sync with ParseKit are:
* OCKPatient <-> User - Note that by default of this framework, any "user" (doctor, patient, caregiver, etc.) is an `OCKPatient` and will have a corresponding record in your Parse `User` table.
* OCKCarePlan <-> CarePlan
* OCKTask <-> Task
* OCKContact <-> Contact
* OCKOutcome <-> Outcome
* OCKOutcomeValue <-> OutcomeValue
* OCKScheduleElement <-> ScheduleElement
* OCKNote <-> Note (I haven't tested Note yet)

I basically sync all usable data for the above entities. For example, `CarePlan` contains:
```swift
    //Parse only
    @NSManaged public var userUploadedToCloud:User?
    @NSManaged public var userDeliveredToDestination:User?
    @NSManaged public var patient:User?
    @NSManaged public var author:User?
    @NSManaged public var authorId:String?
    
    //1 to 1 between Parse and CareStore
    @NSManaged public var title:String
    @NSManaged public var groupIdentifier:String?
    @NSManaged public var tags:[String]?
    @NSManaged public var timezone:String
    @NSManaged public var asset:String?
    @NSManaged public var source:String?
    @NSManaged public var notes:[Note]?
    @NSManaged public var uuid:String
    @NSManaged public var locallyCreatedAt:Date?
    @NSManaged public var locallyUpdatedAt:Date?
    
    //Not 1 to 1 UserInfo fields on CareStore
    @NSManaged public var patientId:String?
```

`locallyCreatedAt` and `locallyUpdatedAt` are exact replicas from the OCK entities and are used to determine the last time an entity has been updated. I found this useful to keep in the Cloud when a patient has the app on multiple devices but you are trying to update the current state of an entity. My guess here is that if versions were kept in the cloud, this might cause an issue unless all versions are related to particular devices.

**Comment by cbaker6** [comment] 2020-05-04 17:29
For some reason, I have unexpected results when using OCKOutcome.id. I can't seem to get back the exact outcome I'm looking for when using fetch which causes incorrect syncing. For example:

```switch
let careKitQuery = OCKOutcomeQuery(id: "x-coredata://842B1364-A6D8-42FE-BA15-D192D8D5EA45/OCKCDTask/p23_8")
                storeManager.store.fetchAnyOutcome(query: careKitQuery, callbackQueue: .global(qos: .background)){
                    result in
                    switch result{
                    case .success(let fetchedOutcome):
                        guard var mutableOutcome = fetchedOutcome as? OCKOutcome else{return}
                        mutableOutcome.remoteID = self.objectId
                        self.values.forEach{
                            for (index,value) in mutableOutcome.values.enumerated(){
                                guard let id = value.userInfo?[kPCKOutcomeValueUserInfoIDKey],
                                    id == $0.uuid else{
                                    continue
                                }
                                mutableOutcome.values[index].remoteID = $0.objectId
                            }
                        }
                        storeManager.store.updateAnyOutcome(mutableOutcome){
                            result in
                            switch result{
                            case .success(let updatedContact):
                                print("Updated remoteID of \(self.parseClassName): \(updatedContact)")
                            case .failure(let error):
                                print("Error updating remoteID. \(error)")
                            }
                        }
                    case .failure(let error):
                        print("Error in \(self.parseClassName).saveAndCheckRemoteID(). \(error)")
                    }
                }
```

This seems to return back random versions of OCKOutcome.id, for example on this one, I got back, `x-coredata://842B1364-A6D8-42FE-BA15-D192D8D5EA45/OCKCDTask/p23_7`. I guess maybe adding , `OCKTaskQuery(for: Date())`, might help here? But then that would require me to know the date.

When I use a dedicated uuid in UserInfo, I don't into this issue, but then again, this can be use case specific

**Comment by erik-apple** [comment] 2020-05-04 21:43
Wow, there's a lot to catch up on here!
I'll go in reverse order!

First, thank you for alerting us to the outcome query bug. `OCKOutcomeQuery` has a `ids` property on it that can be used for querying, but it appears that it is basically ignored, which explains the behavior you're seeing.

**Comment by erik-apple** [comment] 2020-05-04 22:19
The work you're doing on ParseCareKit is really interesting! Thanks so much for sharing it with us.
I'm impressed with the ways in which you managed to associate all the entities without having to drop below the public API.

We've actually been working on a related project ourselves, which we just made public as part of this #426.

We encountered many of the same limitations you did, and we tried to solve them fundamentally by taking steps like adding a `uuid` onto all top level entities and relating entities using their UUID instead of their localDataBaseIDs. I hope that these changes will help with make life easier for you too.

You can read about the details in the PR I linked to above, but the important thing to understand is that the API we are introducing allows synchronization of `OCKStore` with a variety of different backends, but can only be used with `OCKStore`. Specific local database, generic backend. 

If I understand correctly, your ParseCareKit solution ties into a specific backend, but could work with any local store that uses the default CareKit types, since it only relies on the public CareKit API. In that sense, your solution is more generic than ours with respect to the local store. 

We've just created a new 2.0.1 release on the `stable` branch. You'll probably want to point your ParseCareKit dependencies at that tag in the short term. The new work that just landed on master contains a number of small breaking changes that will be part of the 2.1 release. You'll need to make some updates to your source code because of these changes, but we hope they will ultimately make writing packages like ParseCareKit easier for you.

**Comment by cbaker6** [comment] 2020-05-05 19:15
@erik-apple CareKit Remote Synchronization looks interesting. I'm definitely going to take a look. I wonder if makes some of the stuff in ParseCareKit easier.

`If I understand correctly, your ParseCareKit solution ties into a specific backend, but could work with any local store that uses the default CareKit types, since it only relies on the public CareKit API. In that sense, your solution is more generic than ours with respect to the local store.`

Yes, this is true. The backend is specific to Parse (which uses Postgres or Mongo as a DB, I use Postgres for my research based apps that are dependent on CareKit), but the local can be anything that conforms with the `OCKAnyStoreProtocol`. All of the methods for ParseCareKit are designed for `OCKStore`, since the the out-of-box entities provide everything I need. If someone wants to used ParseCareKit with a custom store, there's some basic functionality available, but they will need to write some additional code conforming each of their custom entities to [PCKEntity](https://github.com/netreconlab/ParseCareKit/blob/b0aef2779df22ce7b8dbd1ef49c4262f5e21337d/ParseCareKit/ParseSynchronizedCareKitStoreManager.swift#L17) for it to synchronize properly.

I'll test out the stable branch and will let you know if I find anything. Thanks for letting me know about the breaking changes.

What did you think about the cocoapods part I brought up? I know you [mentioned](https://github.com/carekit-apple/CareKit/issues/383) that new version of CareKit doesn't officially support cocoapods. I'm no cocoapod expert, but I got a working version split into three files (I couldn't figure out how to get it working with 1 file): [CareKit](https://github.com/cbaker6/CareKit/blob/pod/CareKit.podspec), [CareKitUI](https://github.com/cbaker6/CareKit/blob/pod/CareKitUI.podspec), [CareKitStore](https://github.com/cbaker6/CareKit/blob/pod/CareKitStore.podspec). I have ParseCareKit installable via cocoapods leveraging these files, but I don't have the pods pushed to the official cocoapods site since I don't own the CareKit ones.

**Comment by cbaker6** [comment] 2020-05-05 22:14
I managed to get ParseCareKit, it wasn't too bad. It looks like most of the changes are with OCKScheduleElement and switching from localversionId to UUID

**Comment by cbaker6** [comment] 2020-05-06 14:52
I made a [branch](https://github.com/netreconlab/ParseCareKit/tree/remotesynchronize) of ParseCareKit that leverages `OCKRemoteSynchronizable `. On my first pass, it seems like most of the code I wrote can be used with `OCKRemoteSynchronizable` as there will still need to be a translation of OCKEntity's to BackendEntity's. I did run into some road blocks below:

1. I created a class, [ParseRemoteSynchronizationManager](https://github.com/netreconlab/ParseCareKit/blob/remotesynchronize/ParseCareKit/ParseRemoteSynchronizationManager.swift). The problem here is that when converting/synching an `OCKEntity` I need access to `OCKStore` because some entities have relations to others, for example, `OCKCarePlan` can be associated with `OCKPatient`. For this, I query the related patient to make sure I create the same relationship in the cloud. I don't see a way to do this currently because the only way to enable Remote Synchronization (that I see anyways) is to initialize the `OCKStore` with `OCKRemoteSynchronizable` which can't be done if `OCKRemoteSynchronizable` class needs to depend on `OCKStore`. I didn't run into this issue with `OCKSynchronizedStoreManager` as it wrapped the store, so it automatically contains it. The only other two ways I can think of are: 
- Not create relationships between entities on the Backend
- Create methods on the backend that periodically checks for UUIDs of different entities and creates the relationship after the fact

2. Because of the issue above, I wasn't able to test the code. My functionality for `pushRevisions` is below. `addToCloudInBackground` attempts to add an entity, but if it already exists, it attempts to update instead. One thing I can't tell is what the `OCKRevisionRecord` shows for an `OCKEntity` when a "delete" occurs? 

```swift
public func pushRevisions(deviceRevision: OCKRevisionRecord, overwriteRemote: Bool, completion: @escaping (Error?) -> Void) {
        deviceRevision.entities.forEach{
            switch $0{
                
            case .patient(let patient):
                let _ = User(careKitEntity: patient, store: self.store){
                    copiedPatient in
                    guard let patient = copiedPatient as? User else{return}
                    patient.addToCloudInBackground(self.store)
                }
            case .carePlan(let carePlan):
                let _ = CarePlan(careKitEntity: carePlan, store: self.store){
                    copiedCarePlan in
                    guard let carePlan = copiedCarePlan as? CarePlan else{return}
                    carePlan.addToCloudInBackground(self.store)
                }
                
            case .contact(let contact):
                let _ = Contact(careKitEntity: contact, store: self.store){
                    copiedContact in
                    guard let contact = copiedContact as? Contact else{return}
                    contact.addToCloudInBackground(self.store)
                }
            case .task(let task):
                let _ = Task(careKitEntity: task, store: self.store){
                    copiedTask in
                    guard let task = copiedTask as? Task else{return}
                    task.addToCloudInBackground(self.store)
                }
            case .outcome(let outcome):
                let _ = Outcome(careKitEntity: outcome, store: self.store){
                    copiedOutcome in
                    guard let outcome = copiedOutcome as? Outcome else{return}
                    outcome.addToCloudInBackground(self.store)
                }
            }
        }
        completion(nil)
    }
```

3. I'm unsure how to implement `pullRevisions`, mainly due to the `KnowledgeVector`. It seems that based that the `KnowledgeVector` `since` should be used from since->current and all OCKEntities should be fetched from the Backend within that window. From there, a OCKRevisionRecord should be created with all of those entities and that is what's returned in the completion. Is this correct? How would I go about making a KnowledgeVector manually if the Cloud server is based on time? Or how to translate `since` into some form of `time` so I have the beginning time I want to query?

**Comment by erik-apple** [comment] 2020-05-06 16:27
> What did you think about the cocoapods part I brought up? I know you mentioned that new version of CareKit doesn't officially support cocoapods. I'm no cocoapod expert, but I got a working version split into three files (I couldn't figure out how to get it working with 1 file): CareKit, CareKitUI, CareKitStore. I have ParseCareKit installable via cocoapods leveraging these files, but I don't have the pods pushed to the official cocoapods site since I don't own the CareKit ones.

Let's chat about that some more. In addition to the obvious answer that most people are familiar with it already, is there some specific functionality that you gained by adding support for Cocoapods?

**Comment by cbaker6** [comment] 2020-05-06 16:55
> Let's chat about that some more. In addition to the obvious answer that most people are familiar with it already, is there some specific functionality that you gained by adding support for Cocoapods?

Sure... For me, thinking as a standard app developer, SPM is easier to use and manage. Thinking in the case of building tools for remote synchronization using `OCKRemoteSynchronizable` or `OCKSynchronizedStoreManager` in `CareKit`. Many of the api's needed as `VendorSDKs` are not available yet in SPM. This makes it extremely hard to easily package a framework like ParseCareKit which depends on [Parse](https://github.com/parse-community/Parse-SDK-iOS-OSX) which has been out for years and is written in obj-c and in cocoapods (not to mention Parse is dependent on another obj-c dependency that they don't own). I would imagine that other VendorSDKs will run into this issue... I do know that writing an SPM for package file for ParseKit will be very easy, but I suspect it won't work because of the obj-c dependencies I mentioned. If you know of a workaround for this, I can look into it.

At one point, I had used a hybrid of ParseCareKit in SPM and cocoapods, this was tedious to test within my app because I had to manually copy the framework over, clean build folders, etc. 

As an example, this is how I'm currently suggesting people install ParseCareKit https://github.com/netreconlab/ParseCareKit#install-parsecarekit

**Comment by erik-apple** [comment] 2020-05-06 17:11
> I created a class, ParseRemoteSynchronizationManager. The problem here is that when converting/synching an OCKEntity I need access to OCKStore because some entities have relations to others, for example, OCKCarePlan can be associated with OCKPatient. For this, I query the related patient to make sure I create the same relationship in the cloud. I don't see a way to do this currently because the only way to enable Remote Synchronization (that I see anyways) is to initialize the OCKStore with OCKRemoteSynchronizable which can't be done if OCKRemoteSynchronizable class needs to depend on OCKStore.

What you have is a cyclic dependency. Your `ParseRemoteSynchronizationManager` requires a reference to `OCKStore`, and `OCKStore` requires a reference to `ParseRemoteSynchronizationManager`. You can achieve this by using weak references.

```swift
public class ParseRemoteSynchronizationManager: NSObject, OCKRemoteSynchronizable {

   // This needs to be weak to prevent an ARC retain cycle
   // Using a force unwrap ! is not entirely unreasonable either, since store will probably never intentionally be nil
   public weak var store: OCKStore?

   public init() {}

   // ...
}
```

```swift
// Setting up the store
let remote = ParseRemoteSynchronizationManager()
let store = OCKStore(name: "abc", remote: remote)
remote.store = store
let manager = OCKSynchronizedStoreManager(wrapping: store)
```

This gives your `ParseRemoteSynchronizationManager` access to the store, which will allow it to query and perform other book keeping.

------------

> One thing I can't tell is what the OCKRevisionRecord shows for an OCKEntity when a "delete" occurs?

This is something we will need to document. A deleted entity will look exactly like any other entity, but the `deletedDate` property will be non-nil. When a task is deleted, for example, then entity will be an OCKTask. It will have the same `id` as the deleted task, but a new `uuid`. The `deletedDate` will be non-nil, and the `previousVersionUUID` will point to the version of the task from before it was deleted.

----------------

> I'm unsure how to implement pullRevisions, mainly due to the KnowledgeVector. It seems that based that the KnowledgeVector since should be used from since->current and all OCKEntities should be fetched from the Backend within that window. From there, a OCKRevisionRecord should be created with all of those entities and that is what's returned in the completion. Is this correct? How would I go about making a KnowledgeVector manually if the Cloud server is based on time? Or how to translate since into some form of time so I have the beginning time I want to query?

I believe your understanding is correct. Typically in the body of `pullRevisions(since:)`, you will serialize the knowledge vector and send it to a server. The server will inspect the knowledge vector, extracting it's on logical clock. Let's say that it is 7. The server will then leaf through its database and retrieve all entries that stamped with logical timestamp of 7 or greater, package them into a revision record, and send it back to the client.

In the body of the `push(revision:)` method, you serialize the revision and send it to the server. The server should ingest each entity in the revision, stamping each with its current logical clock. Then the server merges the vector it received from the client with its own, and increments its clock. 

You may be more familiar with KnowledgeVectors under their formal name, [Vector Clocks](https://en.wikipedia.org/wiki/Vector_clock). CareKit synchronizes using logical vector clocks instead of wall time because it enables more robust conflict detection. I'm not certain wall time is sufficient for synchronization but you may opt to use wall time if you prefer. 

You'll need to do some booking on your own. Setup a way to persist the last date at which a sync was completed successfully. In the `pull(since:)` method, query Parse objects created after that date and create a revision based on that. If merging the revision is successful, update the last sync date.


---------
A couple other important caveats related to the beta nature of this feature:
1. Right now we only support syncing of OCKTask and OCKOutcome. Support for the other entities will be added once we nail down tasks and outcomes and are confident we've squashed most of the bugs. (You're a few steps ahead of us in ParseCareKit!)
2. The API will be subject to change for the next several months. (We welcome your suggestions too!)
3. Documentation is going to be sparse until the API is hardened. Your best bet is to keep asking questions here.

**Comment by cbaker6** [comment] 2020-05-06 20:13
> This gives your ParseRemoteSynchronizationManager access to the store, which will allow it to query and perform other book keeping.
Thanks! This fixed the issue.

1. Some questions about `OCKRemoteSynchronizable`. I'm assuming it waits until it has a sufficient amount of data before it attempts to synchronize to the Cloud. In some cases, when I added new data, a sync wasn't started immediately, but 20+ seconds later after I added a couple more pieces.
2. When I tested, it kept attempting to sync the data. I did see a `Failed to automatically synchronize. Sync failed: Already busy synchronizing!`. This might be my fault because my `pullRevisions` method is always initializing the KnowledgeVector and I can see `pullRevisions` seems to be called before `pushRevisions` each time.

```
public func pullRevisions(since knowledgeVector: OCKRevisionRecord.KnowledgeVector, mergeRevision: @escaping (OCKRevisionRecord, @escaping (Error?) -> Void) -> Void, completion: @escaping (Error?) -> Void) {
        let revision = OCKRevisionRecord(entities: [], knowledgeVector: .init())
        mergeRevision(revision, completion)
    }
```

A cool thing I added to allow me to test synchronization with the cloud using either `OCKRemoteSynchronizable ` or `OCKSynchronizedStoreManager` is:

```
        var usingRemoteSynchronization = true
        let storeName = "\(kACareKitDatabase)_\(id)_\(type)"
        
        if !usingRemoteSynchronization{
            dataStore = OCKStore(name: storeName, type: .onDisk)
            cloudStoreManager = ParseSynchronizedCareKitStoreManager(dataStoreManager)
        }else{
            remoteStoreManager = ParseRemoteSynchronizationManager()
            dataStore = OCKStore(name: storeName, type: .onDisk, remote: remoteStoreManager)
            remoteStoreManager.store = dataStore
            remoteStoreManager.delegate = self
            remoteStoreManager.automaticallySynchronizes = true
        }
        dataStoreManager = OCKSynchronizedStoreManager(wrapping: dataStore)
```

So I'll test between both as you add/change features.

**Comment by erik-apple** [comment] 2020-05-06 20:45
> Some questions about OCKRemoteSynchronizable. I'm assuming it waits until it has a sufficient amount of data before it attempts to synchronize to the Cloud. In some cases, when I added new data, a sync wasn't started immediately, but 20+ seconds later after I added a couple more pieces.

CareKit attempts to synchronize each time data is added to the store locally. If you add data quickly, then it may try to start a 2nd synchronize before the 1st completes, which will print those errors that you're seeing. That's expected, and it doesn't cause any problems. Anything that's missed will be picked up on the next attempt.

That said, it's best to not make any assumptions about when CareKit will attempt to synchronize. That's something that will definitely be changing in coming months.

> When I tested, it kept attempting to sync the data. I did see a Failed to automatically synchronize. Sync failed: Already busy synchronizing!. This might be my fault because my pullRevisions method is always initializing the KnowledgeVector and I can see pullRevisions seems to be called before pushRevisions each time.

I don't _think_ that the problem is the knowledge vector. If you take a peek at the unit tests for synchronization, you'll see that we typically set the remote's `automaticallySynchronizes` flag to **false** for the purpose of unit testing. That prevents CareKit from trying to do anything clever, and you can control the timing by calling `store.synchronize()` manually. If you `@testable import CareKitStore`, you'll get access to all the synchronous methods we use to make unit testing a bit easier.

**Comment by cbaker6** [comment] 2020-05-11 21:27
> You may be more familiar with KnowledgeVectors under their formal name, Vector Clocks. CareKit synchronizes using logical vector clocks instead of wall time because it enables more robust conflict detection. I'm not certain wall time is sufficient for synchronization but you may opt to use wall time if you prefer.

@ericlewis Thanks for the information on KnowledgeVectors. This was very useful and I was able to fully leverage them in ParseCarerKit with the other updates made in #426. Below are some of the issues I ran into the steps I took to get working as it may help someone else:

Current issues (I'll note if I found a workaround):

- `OCKOutcome.deleteFromCloud` is marked internal. All of the other entities have this as public
- `OCKOutcome.uuid` is marked internal. This might be because of the top-level and version entity discussion we had earlier. The problem here is during syncing, if the uuid isn't pushed to the cloud, I don't see how it can be pulled in pullRevision. *Workaround* I had to resort encoding/decoding of `OCKOutcome` which I later found is required for an `OCKEntity` that is part of a `OCKRevisionRecord`. So this might be the way CareKit wants us to go. I can see how json makes for versatility of exporting/importing. In ParseCareKit, I moved to encoding/decoding the bare minimum, i.e. uuid, createdDate, updatedDate for OCKEntity, and set the mutable types after the entity is created.
- Probably related to above, but there's no way to query by `uuid`. 
- The addition of `UUID's` for each entity caused me to have to do some renaming of fields in order to have similar naming conventions (not too big of a deal), but the one thing I'm unsure of now is there really a difference between `id` and `uuid` besides to ability to set manually `id`?  I guess I'm unsure about the reason for having 2 unique values in 1 entity.

**Comment by cbaker6** [comment] 2020-05-11 21:36
The synchronization for me is fully working. Though I haven't tested out delete because of what I mentioned above. Creating a KnowledgeVector in the cloud that can be merged with the KnowledgeVector in CareKit is fairly straightforward. For ParseCareKit, the initial table construction for this can be done locally and the table is created and added to when pushed. The only issue I had is due to `OCKRevisionRecord.KnowledgeVector`'s initializers, I have to create the KnowledgeVector in json and decode. In the Cloud, the `KnowledgeVector` table consists of each User's KnowledgeVector merged with all of their local vectors along with a field containing the `uuid` of the KnowledgeVector in the cloud:

```
open class KnowledgeVector: PFObject, PFSubclassing {
    //1 to 1 between Parse and CareStore
    @NSManaged public var user:User
    @NSManaged public var vector:String
    @NSManaged public var uuid:String
    
    public static func parseClassName() -> String {
        return kPCKKnowledgeVectorClassKey
    }
    
    public convenience init(uuid:String) {
        self.init()
        self.uuid = uuid
        self.vector = "{\"processes\":[{\"id\":\"\(uuid)\",\"clock\":0}]}"
        guard let thisUser = User.current() else{
            return
        }
        self.user = thisUser
    }
}
```

**Comment by cbaker6** [comment] 2020-05-11 21:45
`pullRevision` and `pushRevision` was pretty much what you described earlier. Though coding it may be a little tricky. These can be seen in [ParseRemoteSynchronizationManager.swift](https://github.com/netreconlab/ParseCareKit/blob/master/ParseCareKit/ParseRemoteSynchronizationManager.swift).

Where pullRevisions is here, https://github.com/netreconlab/ParseCareKit/blob/73427b0e905f28357535a83196e9283033e2d71b/ParseCareKit/ParseRemoteSynchronizationManager.swift#L32

and pushRevisions is here, https://github.com/netreconlab/ParseCareKit/blob/73427b0e905f28357535a83196e9283033e2d71b/ParseCareKit/ParseRemoteSynchronizationManager.swift#L87

**Comment by erik-apple** [comment] 2020-05-16 01:08
I wrote a response to this earlier, but it seems it didn't post correctly. Sorry for leaving you hanging!

The answer to many of your questions, as you guessed, is that we assumed everybody would serialize revision records and entity before sending them off to a server. Under that assumption, many of the properties don't need to have public visibility because they automatically become visible in the serialized representation (typically JSON). We hadn't considered solutions like Parse that require the operations to be defined on-device.

> OCKOutcome.deletedDate is marked internal. All of the other entities have this as public

That probably needs to be made public.

> OCKOutcome.uuid is marked internal.

This is an implementation detail that we didn't intend to make public, but the fact that the server relies on it means we can't easily change it anyway, so there's a strong argument for making it public.

>  Probably related to above, but there's no way to query OCKOutcome by uuid

Since it's currently a private property, we haven't made it queryable. But if we make it public, you're right that it should be queryable.

> I'm unsure of now is there really a difference between id and uuid

`id` is the same for all versions of a task, but the `uuid` is unique for each version.
If you create a task, then update it 4 times, there will be 5 task objects on disk. All 5 of them will have different `uuid`s, but the same `id`.

The `id` property is not strictly required, but allows us to make the API a bit more convenient for developers.

**Comment by erik-apple** [comment] 2020-05-16 01:09
Could you open individual issues for each of the problems you found above? It'll be easier to track them that way!

**Comment by cbaker6** [comment] 2020-05-16 02:19
> The answer to many of your questions, as you guessed, is that we assumed everybody would serialize revision records and entity before sending them off to a server. Under that assumption, many of the properties don't need to have public visibility because they automatically become visible in the serialized representation (typically JSON). We hadn't considered solutions like Parse that require the operations to be defined on-device.

Serializing works for me. I guess I was avoiding encoding/decoding long enough

**Comment by erik-apple** [comment] 2020-05-21 16:19
Have I left any questions unanswered here?
If not, perhaps we can close this issue and track remaining to-dos in the other issues you opened!

**Closed** 2020-05-21 16:21 UTC
