### ISSUE TITLE
[Question] How to update tasks with outcomes?

### ISSUE THREAD

**Issue by tmbiOS** [carekit-apple/CareKit#353] opened 2020-01-30 21:28 UTC
Hello there!
I'm trying to update tasks with the outcome but I get the error "
`Updating task \(task.id) failed. The new version of the task takes effect on \(task.effectiveDate), but an outcome for a previous version of the task exists on \(latestDate). To prevent implicit data loss, you must explicitly delete all outcomes that exist after the new version's `effectiveDate` before applying the update, or move the new version's `effectiveDate` to some date past the latest outcome's date. """`

I want to move the new version's `effectiveDate` to some date past the latest outcome's date but in this function `private func confirmUpdateWillNotCauseDataLoss(tasks: [Task]) throws ` fetching heades from the store.
`let heads: [OCKCDTask] = OCKCDTask.fetchHeads(ids: tasks.map { $0.id }, in: context)`
So It does not affect which effectiveDate I will pass in the new version of the task, because the old tasks are taken and compared against them `if task.effectiveDate <= latestDate.`

So, how to update tasks with outcomes (I can't delete outcomes)?

**Comment by erik-apple** [comment] 2020-01-30 21:58
Thanks for reporting this. We've confirmed it's a bug and are getting a fix ready!

**Comment by erik-apple** [comment] 2020-01-30 23:42
We've just merged a fix for this. Please let us know if it resolves your issue.

**Comment by tmbiOS** [comment] 2020-01-31 07:20
> We've just merged a fix for this. Please let us know if it resolves your issue.
Hi, Erik! Yes, it resolves the issue, but the old crash occurs when the date is changed.
I wrote about it and you've fixed it.
```
let nextInterval = DateInterval(start: nextStartDate, end: nextEndDate)
Fatal error: Reverse intervals are not allowed: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_overlay_Foundation_Sim/swiftlang-1100.2.280/swift/stdlib/public/Darwin/Foundation/DateInterval.swift, line 58
```

**Comment by erik-apple** [comment] 2020-01-31 17:16
Can you provide any other information to help us reproduce the reverse interval bug? It's not occurring on our end. I'd suggest you try reinstalling your app or running it on a new device or simulator. It's possible that your database has gotten into an inconsistence state because of the bug.

If a fresh install of your app doesn't solve the problem, then there must be another bug lurking somewhere. The unit test below passes, which means that updating tasks does work as intended under most circumstances. Perhaps you've stumped across an edge case we're not testing for?  Could you help us out by writing a failing unit test we can use to isolate your problem?

```swift
func testCanUpdateTaskWithOutcomesIfDoesNotCauseDataLoss() throws {
    let schedule = OCKSchedule.mealTimesEachDay(start: Date(), end: nil)
    var task = try store.addTaskAndWait(OCKTask(id: "meds", title: "Medication", carePlanID: nil, schedule: schedule))
    let outcome = OCKOutcome(taskID: try task.getLocalID(), taskOccurrenceIndex: 0, values: [OCKOutcomeValue(1)])
    try store.addOutcomesAndWait([outcome])
    task.effectiveDate = task.schedule[5].start
    XCTAssertNoThrow(try store.updateTaskAndWait(task))
}
```

**Comment by tmbiOS** [comment] 2020-01-31 21:22
@erik-apple You can test like this: (on OCKSample):
1. new installing.
2. add nausea today `outcome`.
3. add 
```
DispatchQueue.main.asyncAfter(deadline: .now() + 4.0) {
          nausea.effectiveDate = nauseaSchedule[5].start
          self.updateTask(nausea) { result in
            print(result)
          }
        }
```
after `addTasks([nausea, doxylamine, kegels], callbackQueue: .main, completion: nil)`
4. After debug print (Success updating) scroll to the next date.
I get crash like this: 
`Fatal error: Reverse intervals are not allowed: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_overlay_Foundation_Sim/swiftlang-1100.2.280/swift/stdlib/public/Darwin/Foundation/DateInterval.swift, line 58`

**Comment by erik-apple** [comment] 2020-02-05 00:22
Thanks for providing a reproducing case. We've been able to replicate this and will begin working on a fix.

**Comment by tmbiOS** [comment] 2020-02-11 17:16
> Thanks for providing a reproducing case. We've been able to replicate this and will begin working on a fix.
@erik-apple Did you manage to fix it?

**Comment by erik-apple** [comment] 2020-02-11 19:21
Yeah, we'll push the fix soon.

**Comment by erik-apple** [comment] 2020-02-11 20:27
Just merged the fix for this! Thanks for reporting it!

**Closed by erik-apple** 2020-02-11 20:27 UTC
