### ISSUE TITLE
CareKit V2 problem in OCKCalendarWeekView

### ISSUE THREAD

**Issue by jwaddilove** [carekit-apple/CareKit#277] opened 2019-06-19 14:01 UTC
Environment iOS 13 Beta 2 (iPad & iPhone)
CareKit V2 Beta: commit a82e11b
 
I’m trying to develop a simple Care Kit App that helps manage multiple different medication doses, each with a different schedule. The App also assists in tracking patient pain.
 
Initially I am populating a test Store with a simple code based care plan. The OCKDailyPageViewController is set to use OCKSimpleLogTaskViewController, OCKChecklistTaskViewController, OCKSimpleTaskView, and OCKCartesianChartViewController.
 
I seem to get a hard crash in OCKCalendarWeekView updateRingLabels:
  completionRingButtons[i].setTitle(dateFormatter.string(from: date), for: .normal)
 
A bit of digging around and I find that the OCKSample app included in the beta has the same problem, any suggestions?
 
A second question:
 
I need to use a care plan where the Prednisolone dose is reduced each month. Is this an example of where a Task should use multiple versions (any documentation yet) or should it be multiple tasks? Ideally I want a chart that can show pain tracking against Prednisolone adherence over time.
 
Thank you,  Jonathan

( I have also posted this in the Apple Developer forums as I am not sure which is the preferred channel for feedback)

**Comment by erik-apple** [comment] 2019-06-19 16:08
Thanks for letting us know about this issue! Can you describe the steps to reproduce it in the sample app? Does it happen when paging between days or something? If we can reproduce it, we'll get it fixed right up!

**Comment by jwaddilove** [comment] 2019-06-19 16:21
I'm on beta 2 for iOS & Xcode, iPad Pro. Just run the sample app and a blank (white) screen appear before any UI is visible and I get the crash.  I'm attempting to attach the crash log...

Let me know if there is more I can do to help. I'm starting to get interest from GP's and Consultants on what's possible so I'd like to be able to move forward.  Many thanks Jonathan


[OCKSample  19-06-2019, 15-39.txt](https://github.com/carekit-apple/CareKit/files/3306999/OCKSample.19-06-2019.15-39.txt)

**Comment by erik-apple** [comment] 2019-06-19 16:29
Thanks, I'll begin looking into this. In the meantime, can you confirm whether or not it works on an iPhone?

**Comment by jwaddilove** [comment] 2019-06-19 16:40
I can confirm that I get the same crash on an iPhone XS.

Thank you for the suggestion about adjusting the dose rate. I think I will need to go down the versioning route. There is a care plan in place that could use your first suggestion to phase changes over time. But we had a meeting  with the consultant that resulted in an immediate change to the existing plan. I guess I'm going to have to learn the versioning system ;-)

Many thanks

**Comment by erik-apple** [comment] 2019-06-19 18:02
We haven't been able to reproduce this on our end yet, so we have a few more questions for you.

First and foremost, can you provide us with a screenshot of the call stack when it crashes, as well as the value of `i` and `date` in `completionRingButtons[i].setTitle(dateFormatter.string(from: date), for: .normal)`?

Based on your crash log, it looks like the issue is related to formatting the date. Can you also tell us what your locale and date/time settings are?

Have you made any modifications at all to the sample app, such as changing the date of the tasks, that we might need to replicate to get the same crash?

**Comment by jwaddilove** [comment] 2019-06-19 18:44
Hi Erik,

I can confirm  it's a problem with Locale date formatting.

I'm in the UK, when I switch the iPad's region to US the sample app (& my app) run OK.

Do you still need the screenshot?  

I'm happy to apply a local fix if you want me to test anything.

Thank you for the help   Jonathan

**Comment by erik-apple** [comment] 2019-06-20 00:08
We've been able to replicate this now and are working on a solution. While you're waiting on the fix, you can develop on a simulator or device with a different locale. I've confirmed that `en_US` and `en_AU` both work properly.

**Comment by jwaddilove** [comment] 2019-06-20 06:15
Thank you, I'm happy and will watch for a fix

**Comment by erik-apple** [comment] 2019-06-20 20:00
We just merged a PR that fixes this issue! Thanks for helping us find this bug!

**Closed** 2019-06-20 19:59 UTC
