### ISSUE TITLE
V2 interoperability with current ResearchKit

### ISSUE THREAD

**Issue by jwaddilove** [carekit-apple/CareKit#305] opened 2019-07-17 14:28 UTC
I’m at the point of wanting to add pain score questions to my V2 app. The old V1 sample showed how to do this by building an `ORKOrderedTask`. Attempting the same approach with V2 CareKit fails:
> Cannot convert value of type 'ORKOrderedTask' to expected element type 'OCKTask'

Am I taking the wrong design approach or is the integration with ResearchKit not available yet?

Thank you for your help, Jonathan

**Comment by erik-apple** [comment] 2019-07-17 17:44
Jonathan, can you provide more context for the problem you are experiencing? Can you point out the code in the old sample app that you are trying to replicate.

The error message leads me to believe you are trying to pass a ResearchKit task into a function that expects to receive a CareKit task.

**Comment by jwaddilove** [comment] 2019-07-17 18:07
Erik,

Sorry for the lack of context... My first pass is pretty much a cut and paste from the V1 sample, my code is:

```
		let question = "On a scale from 1 to 10, how would you rate your pain this morning?"
		let maximumValueDescription = "Bad"
		let minimumValueDescription = "Good"
		
		
		// Create a question and answer format.
		let answerFormat = ORKScaleAnswerFormat(
			maximumValue: 10,
			minimumValue: 1,
			defaultValue: -1,
			step: 1,
			vertical: false,
			maximumValueDescription: maximumValueDescription,
			minimumValueDescription: minimumValueDescription
		)
		
		
		let questionStep = ORKQuestionStep(identifier: "morningPainQuestion", title: question, answer: answerFormat)
		questionStep.isOptional = false
		
		// Create an ordered task with a single question.
		let task = ORKOrderedTask(identifier: "morningPain", steps: [questionStep])
	
storeManager.store.addTasks([task])
```

Where `storeManager: OCKSynchronizedStoreManager<Store>` is my V2 code and Xcode fails on the `addTasks` line.

Many thanks

**Comment by erik-apple** [comment] 2019-07-17 21:28
I think the place where you're getting tripped up is that CareKit tasks and ResearchKit tasks are distinct from one another, and cannot be used interchangeably.

CareKit and ResearchKit are compatible though, and they are meant to be used together. The strategy you should follow is to setup a button to present a ResearchKit view controller, set your view controller as the ResearchKit view controller's delegate so that you can get a callback when the survey is complete, and finally to extract the result from the ResearchKit view controller and save it in CareKit.

Examples of each step are below, and full code is at the end. This code is not production ready, but it'll get you on the right path.

#### Setup a button to present an RK view controller
You would do this in the sample app's `CareViewController`. Rewiring an existing button is a reasonable approach. You could also add a new button.

```swift
let nauseaCard = OCKSimpleLogTaskViewController(
    storeManager: self.storeManager,
    task: nauseaTask,
    eventQuery: OCKEventQuery(for: date))

// Rewire the log button to present a ResearchKit survey instead of saving an outcome
nauseaCard.taskView.logButton.removeTarget(nil, action: nil, for: .allEvents)
nauseaCard.taskView.logButton.addTarget(self, action: #selector(self.presentSurvey), for: .touchUpInside)
nauseaCard.taskView.logButton.setTitle("Enter Pain Level", for: .normal)

listViewController.appendViewController(nauseaCard, animated: true)
```

#### Create and present an RK view controller
This will be performed when the button above is tapped.

```swift
// Create and present a ResearchKit survey to the user
@objc func presentSurvey() {
    let answerFormat = ORKScaleAnswerFormat(maximumValue: 10, minimumValue: 0, defaultValue: 5, step: 1)
    let questionStep = ORKQuestionStep(identifier: "question", title: "Pain level", question: "What is your pain level?", answer: answerFormat)
    let surveyTask = ORKOrderedTask(identifier: "pain", steps: [questionStep])
    let surveyController = ORKTaskViewController(task: surveyTask, taskRun: nil)
    surveyController.delegate = self // Don't forget this!

    present(surveyController, animated: true, completion: nil)
}
```

#### Retrieve the result from the ResearchKit view controller
When ResearchKit has finished its job, you need to get the result from it.

```swift
// This will be triggered when the user completes the ResearchKit survey
func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?) {
    switch reason {
    case .completed:

        // Get the result out of the ResearchKit view controller
        taskViewController.dismiss(animated: true, completion: nil)
        guard let pain = taskViewController.result.results?.filter({ $0.identifier == "question" }).first as? ORKStepResult else { return }
        let scalePain = pain.results![0] as! ORKScaleQuestionResult
        let painLevel = scalePain.answer as! Int // This is the pain level score that we want!

    default: fatalError("Handle other reasons properly please!")
    }
}
```

#### Save the result to CareKit's store
Finally, you need to save the result to the store. This part is a little bit trickier than the other steps because we have to figure out which event the outcome needs to be associated with. For this demo, we'll just use the first event on the currently selected day.

```swift
// Fetch the task you want to save the result to
storeManager.store.fetchTask(withIdentifier: "nausea") { result in
    let task = try! result.get()

    // Figure out what event to save the outcome on
    let thisMorning = Calendar.current.startOfDay(for: self.selectedDate)
    let tonight = Calendar.current.date(byAdding: DateComponents(day: 1, second: -1), to: thisMorning)!
    let scheduleEvent = task.schedule.events(from: thisMorning, to: tonight).first!

    // Create a CareKit outcome from the ResearchKit result
    let outcome = OCKOutcome(taskID: task.localDatabaseID, taskOccurenceIndex: scheduleEvent.occurence, values: [OCKOutcomeValue(painLevel)])

    // Save the outcome into CareKit
    self.storeManager.store.addOutcomes([outcome])
}
```

That's all there is to it!
You can present and save results from any ResearchKit modules using this same basic flow. Note that if your ResearchKit survey returns more than one result, you can give our CareKit outcome multiple values.

Here's the full code if you want to use it for reference.

```swift
/*
 Copyright (c) 2019, Apple Inc. All rights reserved.
 
 Redistribution and use in source and binary forms, with or without modification,
 are permitted provided that the following conditions are met:
 
 1.  Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 
 2.  Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation and/or
 other materials provided with the distribution.
 
 3. Neither the name of the copyright holder(s) nor the names of any contributors
 may be used to endorse or promote products derived from this software without
 specific prior written permission. No license is granted to the trademarks of
 the copyright holders even if such marks are included in this software.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import Foundation
import UIKit
import CareKit
import ResearchKit

class CareViewController: OCKDailyPageViewController<OCKStore>, ORKTaskViewControllerDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.rightBarButtonItem =
            UIBarButtonItem(title: "Care Team", style: .plain, target: self,
                            action: #selector(presentContactsListViewController))
    }

    @objc private func presentContactsListViewController() {
        let viewController = OCKContactsListViewController(storeManager: storeManager)
        viewController.title = "Care Team"
        viewController.navigationItem.rightBarButtonItem =
            UIBarButtonItem(title: "Done", style: .plain, target: self,
                            action: #selector(dismissContactsListViewController))

        let navigationController = UINavigationController(rootViewController: viewController)
        present(navigationController, animated: true, completion: nil)
    }

    @objc private func dismissContactsListViewController() {
        dismiss(animated: true, completion: nil)
    }

    // This will be called each time the selected date changes.
    // Use this as an opportunity to rebuild the content shown to the user.
    override func dailyPageViewController<S>(
        _ dailyPageViewController: OCKDailyPageViewController<S>,
        prepare listViewController: OCKListViewController,
        for date: Date) where S: OCKStoreProtocol {

        let identifiers = ["doxylamine", "nausea", "kegels"]
        let anchor = OCKTaskAnchor.taskIdentifiers(identifiers)
        var query = OCKTaskQuery(for: date)
        query.excludesTasksWithNoEvents = true

        storeManager.store.fetchTasks(anchor, query: query) { result in
            switch result {
            case .failure(let error): print("Error: \(error)")
            case .success(let tasks):

                // Add a non-CareKit view into the list
                let tipTitle = "Benefits of exercising"
                let tipText = "Learn how activity can promote a healthy pregnancy."

                // Only show the tip view on the current date
                if Calendar.current.isDate(date, inSameDayAs: Date()) {
                    let tipView = TipView()
                    tipView.headerView.titleLabel.text = tipTitle
                    tipView.headerView.detailLabel.text = tipText
                    tipView.imageView.image = UIImage(named: "exercise.jpg")
                    listViewController.appendView(tipView, animated: false)
                }

                // Since the kegel task is only sheduled every other day, there will be cases
                // where it is not contained in the tasks array returned from the query.
                if let kegelsTask = tasks.first(where: { $0.identifier == "kegels" }) {
                    let kegelsCard = OCKSimpleTaskViewController(storeManager: self.storeManager,
                                                                 task: kegelsTask,
                                                                 eventQuery: OCKEventQuery(for: date))
                    listViewController.appendViewController(kegelsCard, animated: false)
                }

                // Create a card for the doxylamine task if there are events for it on this day.
                if let doxylamineTask = tasks.first(where: { $0.identifier == "doxylamine" }) {
                    let doxylamineCard = OCKChecklistTaskViewController(
                        storeManager: self.storeManager,
                        task: doxylamineTask,
                        eventQuery: OCKEventQuery(for: date))

                    listViewController.appendViewController(doxylamineCard, animated: false)
                }

                // Create a card for the nausea task if there are events for it on this day.
                // Its OCKSchedule was defined to have daily events, so this task should be
                // found in `tasks` every day after the task start date.
                if let nauseaTask = tasks.first(where: { $0.identifier == "nausea" }) {
                    // Create a plot comparing nausea to medication adherence.
                    let nauseaDataSeries = OCKCartesianChartViewController<OCKStore>.DataSeriesConfiguration(
                        taskIdentifier: "nausea",
                        legendTitle: "Nausea",
                        gradientStartColor: #colorLiteral(red: 0.9176470588, green: 0.3529411765, blue: 0.4588235294, alpha: 1),
                        gradientEndColor: #colorLiteral(red: 0.9020889401, green: 0.5339772701, blue: 0.4407126009, alpha: 1),
                        markerSize: 10,
                        eventAggregator: OCKEventAggregator.countOutcomeValues)

                    let doxylamineDataSeries = OCKCartesianChartViewController<OCKStore>.DataSeriesConfiguration(
                        taskIdentifier: "doxylamine",
                        legendTitle: "Doxylamine",
                        gradientStartColor: #colorLiteral(red: 0.7372466922, green: 0.7372466922, blue: 0.7372466922, alpha: 1),
                        gradientEndColor: #colorLiteral(red: 0.7372466922, green: 0.7372466922, blue: 0.7372466922, alpha: 1),
                        markerSize: 10,
                        eventAggregator: OCKEventAggregator.countOutcomeValues)

                    let insightsCard = OCKCartesianChartViewController(
                        storeManager: self.storeManager,
                        dataSeriesConfigurations: [nauseaDataSeries, doxylamineDataSeries],
                        date: date,
                        plotType: .bar)

                    let titleText = "Nausea & Doxylamine Intake"
                    let detailText = "This Week"

                    insightsCard.chartView.headerView.titleLabel.text = titleText
                    insightsCard.chartView.headerView.detailLabel.text = detailText

                    listViewController.appendViewController(insightsCard, animated: false)

                    // Also create a card that displays a single event.
                    // The event query passed into the initializer specifies that only
                    // today's log entries should be displayed by this log task view controller.
                    let nauseaCard = OCKSimpleLogTaskViewController(
                        storeManager: self.storeManager,
                        task: nauseaTask,
                        eventQuery: OCKEventQuery(for: date))

                    // Rewire the log button to present a ResearchKit survey instead of saving an outcome
                    nauseaCard.taskView.logButton.removeTarget(nil, action: nil, for: .allEvents)
                    nauseaCard.taskView.logButton.addTarget(self, action: #selector(self.presentSurvey), for: .touchUpInside)
                    nauseaCard.taskView.logButton.setTitle("Enter Pain Level", for: .normal)

                    listViewController.appendViewController(nauseaCard, animated: true)
                }
            }
        }
    }

    // Create and present a ResearchKit survey to the user
    @objc func presentSurvey() {
        let answerFormat = ORKScaleAnswerFormat(maximumValue: 10, minimumValue: 0, defaultValue: 5, step: 1)
        let questionStep = ORKQuestionStep(identifier: "question", title: "Pain level", question: "What is your pain level?", answer: answerFormat)
        let surveyTask = ORKOrderedTask(identifier: "pain", steps: [questionStep])
        let surveyController = ORKTaskViewController(task: surveyTask, taskRun: nil)
        surveyController.delegate = self

        present(surveyController, animated: true, completion: nil)
    }

    // This will be triggered when the user completes the ResearchKit survey
    func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?) {
        switch reason {
        case .completed:

            // Get the result out of the ResearchKit view controller
            taskViewController.dismiss(animated: true, completion: nil)
            guard let pain = taskViewController.result.results?.filter({ $0.identifier == "question" }).first as? ORKStepResult else { return }
            let scalePain = pain.results![0] as! ORKScaleQuestionResult
            let painLevel = scalePain.answer as! Int

        // Add the result into CareKit store
        storeManager.store.fetchTask(withIdentifier: "nausea") { result in
            let task = try! result.get()
            let thisMorning = Calendar.current.startOfDay(for: self.selectedDate)
            let tonight = Calendar.current.date(byAdding: DateComponents(day: 1, second: -1), to: thisMorning)!
            let scheduleEvent = task.schedule.events(from: thisMorning, to: tonight).first!
            let outcome = OCKOutcome(taskID: task.localDatabaseID, taskOccurenceIndex: scheduleEvent.occurence, values: [OCKOutcomeValue(painLevel)])
            self.storeManager.store.addOutcomes([outcome])
        }

        default: fatalError("Handle other reasons properly please!")
        }
    }
}
```

**Comment by jwaddilove** [comment] 2019-07-18 13:49
Thank you for the very full and clear explanation, that has been very helpful and I am adopting the approach you describe.

The only issue I have  is the 
`present(surveyController, animated: true, completion: nil)`

This fails 
> [MyCare.AppDelegate window]: unrecognized selector sent to instance  

If I try and present a `UIViewController` or an `OCKContactsListViewController` it all works... Is there anything I'm missing (I'm using the ResearchKit from gitHub).

Again, thank you for taking valuable time to code the example.

**Comment by erik-apple** [comment] 2019-07-18 15:10
Can you post a stack trace of the place that it’s crashing? That’ll help us pinpoint the issue!

**Comment by jwaddilove** [comment] 2019-07-18 15:41
Does this help or do you need more?

```

2019-07-18 16:35:27.089359+0100 MyCare[1390:727991] -[MyCare.AppDelegate window]: unrecognized selector sent to instance 0x2828d05c0
2019-07-18 16:35:27.091036+0100 MyCare[1390:727991] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MyCare.AppDelegate window]: unrecognized selector sent to instance 0x2828d05c0'
*** First throw call stack:
(0x18684b340 0x186566388 0x186749f0c 0x18a88f45c 0x18684f740 0x1868518b0 0x102ce5714 0x102ce4f30 0x102ce38fc 0x102c9c370 0x102c9c124 0x102cdb36c 0x102e4b370 0x102e4c5e8 0x18a23bec4 0x18a240adc 0x18a240ec8 0x18a1ce6c0 0x18a1ce93c 0x102c55028 0x102c528d8 0x18a246364 0x18a246a04 0x18a161130 0x18a24e290 0x18a86a39c 0x18a859f7c 0x18a88a8bc 0x1867c5e94 0x1867c0b34 0x1867c10e4 0x1867c08b0 0x190d9a534 0x18a860d34 0x1021a347c 0x186641764)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) po Thread.callStackSymbols
▿ 14 elements
  - 0 : "0   ???                                 0x00000001102e066c 0x0 + 4566419052"
  - 1 : "1   MyCare                              0x00000001021a3430 main + 0"
  - 2 : "2   libsystem_c.dylib                   0x00000001864e7af4 abort + 104"
  - 3 : "3   libc++abi.dylib                     0x00000001865fe3c8 __cxa_bad_cast + 0"
  - 4 : "4   libc++abi.dylib                     0x00000001865fe5c0 88CCA8CB-75C5-3987-A3F7-3DE3FBBC294A + 5568"
  - 5 : "5   libobjc.A.dylib                     0x0000000186566668 49456FE4-A47C-3608-BB65-38150E4A098A + 26216"
  - 6 : "6   libc++abi.dylib                     0x000000018660b634 88CCA8CB-75C5-3987-A3F7-3DE3FBBC294A + 58932"
  - 7 : "7   libc++abi.dylib                     0x000000018660b1ec __cxa_rethrow + 148"
  - 8 : "8   libobjc.A.dylib                     0x000000018656654c objc_exception_rethrow + 44"
  - 9 : "9   CoreFoundation                      0x00000001867c0920 CFRunLoopRunSpecific + 592"
  - 10 : "10  GraphicsServices                    0x0000000190d9a534 GSEventRunModal + 108"
  - 11 : "11  UIKitCore                           0x000000018a860d34 UIApplicationMain + 1940"
  - 12 : "12  MyCare                              0x00000001021a347c main + 76"
  - 13 : "13  libdyld.dylib                       0x0000000186641764 EF740785-C0C1-329E-9633-ED68B48DEA11 + 5988"

```

many thanks

**Comment by akshay-yadav-apple** [comment] 2019-07-18 17:11
Hey! @jwaddilove 
Are you using current master of ResearchKit?
Can you attach the code where you are creating the ORKTaskViewController instance. It'd be helpful to see the whole file where you are creating and using these ResearchKit and CareKit tasks. Are you using the code exactly as @erik-apple suggested.

**Comment by jwaddilove** [comment] 2019-07-18 18:12
I downloaded the ResearchKit on 20 June. I hope I'm doing exactly what Erik suggested. The `ORKTaskViewController` is created the the extension at the end of the file.... 

This is very much a sandpit where I'm trying to get to grips with the V2 framework, not very swifty and no quality statement 
[CareViewController.swift.zip](https://github.com/carekit-apple/CareKit/files/3407862/CareViewController.swift.zip)
:-)

Thank you for helping

**Comment by erik-apple** [comment] 2019-07-18 21:53
@jwaddilove Your code runs on my system without any problems. 

It's hard to troubleshoot since we can't reproduce the problem. If you've cloned the most recent version of CareKit, then you're using the same version of CareKit and ResearchKit as us. It could be related to the version of Xcode you're running (I have Xcode 11 beta 4 on Catalina beta 4), but the error makes me think it's something more simple than that, but I'm not sure what.

When it gives you the `[MyCare.AppDelegate window]: unrecognized selector sent to instance` error, can you try to figure out what the name of the selector is that is unrecognized? That should get us back on track.

**Comment by jwaddilove** [comment] 2019-07-19 14:06
OK, I’ve had a little bit of success.

For the record I’m on Beta 4 everywhere and I have taken a fresh clone of ResearchKit and cleaned folders. The problem is the same.

However, my project was based on an Xcode 11 template and includes a `SceneDelegate`, also this template generates an AppDelegate without `var window: UIWindow`. On a whim I added the `var window: UIWindow` to the AppDeleagte and, _hey presto_, the `present(surveyController, animated: true, completion: nil)` now appears.

I notice that the V2 sample doesn’t include a SceneDelegate, but does have a `var window` in the app delegate…

I’m not yet familiar enough with the new SceneDelegate concept to understand the Best Practice solution for this.

Once again, thank you for the time and energy you have spent on this issue

**Comment by erik-apple** [comment] 2019-07-19 21:50
Glad you got it worked out! I’ll go ahead and close this issue out!

**Closed by erik-apple** 2019-07-19 21:50 UTC

**Comment by scdi** [comment] 2019-10-12 15:17
I understand that this issue is closed but I am not sure that it is not broken again. the problem is in finding the OCKSimpleLogTaskViewController. I use the latest version of CareKit and ResearchKit with Xcode 11. The error is "Use of unresolved identifier 'OCKSimpleLogTaskViewController'"
Is possible that 'OCKSimpleLogTaskViewController' cannot be found. Some of the CareKit downloads (as of 12-OCT-2019) do not have that file at all.

**Comment by erik-apple** [comment] 2019-10-12 17:55
@scdi The simple log task view controller has been renamed to `OCKButtonLogTaskViewController`. 

The new API can be seen in the sample app's `CareViewController.swift` file.
```swift
// Also create a card that displays a single event.
// The event query passed into the initializer specifies that only
// today's log entries should be displayed by this log task view controller.
let nauseaCard = OCKButtonLogTaskViewController(
    storeManager: self.storeManager,
    task: nauseaTask,
    eventQuery: OCKEventQuery(for: date))
```

We received feedback (#273) and pull requests from other users like @pgallastegui who wanted to be able to add more buttons for logging different values. Based on this community input, we decided to extend what used to be the simple log task view controller to support multiple buttons, also changing the name to reflect its new capabilities.

**Comment by scdi** [comment] 2019-10-12 20:10
Thanks so much for the prompt reply. I tried OCKButtonLogTaskViewController and get this error: Value of type 'OCKButtonLogTaskViewController<OCKStore>' has no member 'taskView' for the codes suggested before 
nauseaCard.taskView.logButton.removeTarget(nil, action: nil, for: .allEvents)
nauseaCard.taskView.logButton.addTarget(self, action: ......

**Comment by erik-apple** [comment] 2019-10-14 17:01
@scdi There are two kinds of task view controllers, those that display multiple events and those that only display one event. 

The checklist and grid task view controllers are examples of view controllers that can display multiple events. These view controllers have a `taskView` property and their viewModel property is of type `OCKTask`. 

The button log view controller only displays a single event (with multiple outcome values). View controllers of this variety have an `eventView` property and their viewModel property is of type `OCKEvent`.

You can access the view via the `eventView` property, but it will not be especially useful to you because the view is now a collection view capable of displaying multiple buttons. You could access the cells on the collection and add targets to the buttons, but that solution would probably be a bit too fragile.

Given the changes that have been made to `OCKButtonLogViewController`, I would now suggest that you're best bet is to subclass `OCKButtonLogViewController` and override its `eventView(_ eventView: UIView & OCKEventDisplayable,  didCreateOutcomeValueAt index: Int, sender: Any?)` method as I've demonstrated below.

```swift
class MyResearchKitLogTaskViewController<Store: OCKStoreProtocol>: OCKButtonLogTaskViewController<Store>, ORKTaskViewControllerDelegate {

    override func eventView(_ eventView: UIView & OCKEventDisplayable,
                            didCreateOutcomeValueAt index: Int,
                            sender: Any?) {

        // Note: Do not call super.eventView(_:didCreateValueAt:sender:) to prevent the 
        // default behavior of saving a new outcome value.

        // Create and present ResearchKit view controller here.
        
    }

    func taskViewController(_ taskViewController: ORKTaskViewController,
                            didFinishWith reason: ORKTaskViewControllerFinishReason,
                            error: Error?) {

        // Save new outcome to store here. (See examples in previous posts)
    }
}
```

Going this route allows you to encapsulate all of the ResearchKit interop code in a single view controller and keeps your app well organized. I think this should work well for you!

**Comment by scdi** [comment] 2019-10-15 03:35
Thank you so much. That worked like a charm.

**Comment by reetm09** [comment] 2020-02-29 11:00
I've been following through these steps to integrate the ResearchKit survey as an outcome of the log button. However, when I try erik-apple's solution, it gives the following error for eventView: "Method does not override any method from its superclass." How can I resolve this error?

Thanks!

**Comment by reetm09** [comment] 2020-02-29 11:02
I've been following through these steps to integrate the ResearchKit survey as an outcome of the log button. However, when I try erik-apple's solution, it gives the following error for eventView: "Method does not override any method from its superclass." How can I resolve this error?

Thanks!

**Comment by gavirawson-apple** [comment] 2020-03-04 02:59
The API has been updated since this issue. This should do the trick:

```swift

class MyResearchKitLogTaskViewController<Store: OCKStoreProtocol>: OCKButtonLogTaskViewController, ORKTaskViewControllerDelegate {

    override func taskView(_ taskView: UIView & OCKTaskDisplayable, didCreateOutcomeValueAt index: Int, eventIndexPath: IndexPath, sender: Any?) {
        // Note: Do not call super to prevent the default behavior of saving a new outcome value.

        // Create and present ResearchKit view controller here.
    }

    func taskViewController(_ taskViewController: ORKTaskViewController,
                            didFinishWith reason: ORKTaskViewControllerFinishReason,
                            error: Error?) {
        // Save new outcome to store here. (See examples in previous posts)
    }
}
```

**Comment by reetm09** [comment] 2020-03-05 22:13
Thanks so much!
