### ISSUE TITLE
Future tasks not working correctly

### ISSUE THREAD

**Issue by nizar** [carekit-apple/CareKit#545] opened 2021-01-28 20:18 UTC
Hello, I'm working on a project using CareKit and have run into an odd issue. When a task has a schedule that starts in the future, the view controllers cannot find the event and thus not able to display. The easiest way to re-create this is to change the OCKSample app populateSampleData() to add tasks starting in the future rather than past. Change https://github.com/carekit-apple/CareKit/blob/7dfcdef4de7e91449e86ac963043b44188a6ba31/OCKSample/OCKSample/AppDelegate.swift#L72 to

`let aFewDaysAgo = Calendar.current.date(byAdding: .day, value: 1, to: thisMorning)!`

This results in the task view controllers failing to render the content of the specific tasks.

The closest I've come to tracking this down is that the query to find a task is limited to the current date in
https://github.com/carekit-apple/CareKit/blob/7dfcdef4de7e91449e86ac963043b44188a6ba31/CareKitStore/CareKitStore/Protocols/Tasks/OCKAnyTaskStore.swift#L120

Is there a different/better way to create tasks with a future schedule?

Thanks!

**Comment by erik-apple** [comment] 2021-01-28 21:28
The method that you discovered is convenience method we provide for looking up the definition of a task on the current date.

```swift
public extension OCKAnyReadOnlyTaskStore {
    func fetchAnyTask(withID id: String, callbackQueue: DispatchQueue = .main, completion: @escaping OCKResultClosure<OCKAnyTask>) {
        var query = OCKTaskQuery(for: Date())
        query.extendedSortDescriptors = [.effectiveDate(ascending: true)]
        query.ids = [id]
        query.limit = 1
        fetchAnyTasks(query: query, callbackQueue: callbackQueue, completion:
            chooseFirst(then: completion, replacementError: .fetchFailed(reason: "No task with matching ID")))
    }
}
```

If you'd like to query into the future, you can create your own query.

```swift
var query = OCKTaskQuery(for: futureDate)
query.ids = ["doxylamine"]

storeManager.store.fetchAnyTasks(query: query, callbackQueue: .main) { result in 
   let task = try result.get().first! // This will be your task as defined on `futureDate`
}
```

The reason the cards are empty is because you're creating a task view controller for `today` and telling it to display a task that hasn't come into existence yet. Under the hood, CareKit is trying to find a task with the id you gave on the date you gave it, but there isn't one, so it has nothing to display. This is considered a programmer error.

Following the example in the sample app, you should query for tasks to ensure that they exist on a given day before you create a task view controller for them.

https://github.com/carekit-apple/CareKit/blob/7dfcdef4de7e91449e86ac963043b44188a6ba31/OCKSample/OCKSample/CareViewController.swift#L67-L76

**Comment by nizar** [comment] 2021-01-31 02:10
I spent some more time looking into this and it appears to be a general problem with OCKStoreCoordinator.fetchAnyEvents. What I'm seeing is that if two tasks are created such that taskA has a startDate of today (Date()) and taskB has a startDate of tomorrow (Date() + 1 day), any call to coordinator.fetchAnyEvents(taskID: "taskB", query: OCKEventQuery(for: tomorrow)), will not find events for taskB. In fact, taskB itself is not found because no store is found for that particular taskID since the findStore call restricts the query to Date().

A unit test to demonstrate this is at https://github.com/nizar/CareKit/blob/2784a4b073837478033461e21e0ede7702cfba7f/CareKitStore/CareKitStoreTests/TestPersistentStoreCoordinator.swift#L195-L266

A potential fix for this is at
https://github.com/nizar/CareKit/commit/2784a4b073837478033461e21e0ede7702cfba7f

**Comment by erik-apple** [comment] 2021-02-04 01:24
Yes, I think your diagnosis is correct. Thanks for digging so deep into that!

As for the solution, there's one tweak you'll need to add, I think. The sort order should be changed to descending as well. This will ensure that the query returns the most up to date version of the task. For the purpose of `OCKStoreCoordinator`, it doesn't really matter which version it returns, but in other contexts it does.

```swift
// Change to the source code (line 118 of `OCKAnyTaskStore.swift`)
public extension OCKAnyReadOnlyTaskStore {
    func fetchAnyTask(withID id: String, callbackQueue: DispatchQueue = .main, completion: @escaping OCKResultClosure<OCKAnyTask>) {
        var query = OCKTaskQuery(id: id)
        query.extendedSortDescriptors = [.effectiveDate(ascending: false)]
        query.limit = 1
        fetchAnyTasks(query: query, callbackQueue: callbackQueue, completion:
            chooseFirst(then: completion, replacementError: .fetchFailed(reason: "No task with matching ID")))
    }
}
```

And let's use this more targeted unit test. The root cause was that the `fetchAnyTask(id:)` method wasn't returning the newest version of the task, so let's write our test against that!

```swift
    // Unit test for the fetch function that caused the issue. Add this at line 413 of `TestStore+Tasks.swift`
    func testFetchTaskByIdConvenienceMethodReturnsNewestVersionOfTask() throws {
        let schedule = OCKSchedule.dailyAtTime(hour: 0, minutes: 0, start: Date(), end: nil, text: nil)
        var taskV1 = OCKTask(id: "task", title: "V1", carePlanUUID: nil, schedule: schedule)
        taskV1 = try store.addTaskAndWait(taskV1)

        var taskV2 = taskV1
        taskV2.title = "V2"
        taskV2.effectiveDate = Calendar.current.date(byAdding: .year, value: 1, to: Date())!
        taskV2 = try store.updateTaskAndWait(taskV2)

        let expect = expectation(description: "Fetches V2")
        store.fetchAnyTask(withID: "task") { result in
            let task = try? result.get()
            XCTAssert(task?.title == "V2")
            expect.fulfill()
        }
        waitForExpectations(timeout: 0.1, handler: nil)
    }
```

Would you like to submit another PR to patch this up? I can do it for you if you'd like, but since you do did the leg work, you should get the credit!

**Comment by nizar** [comment] 2021-02-04 17:01
Thanks for following up @erik-apple. I'm happy to submit a PR with the changes.

**Comment by erik-apple** [comment] 2021-03-29 17:53
Thanks for submitting a fix for this @nizar!

**Closed by erik-apple** 2021-03-29 17:53 UTC
