### ISSUE TITLE
OCKDocument containing OCKBarChart does not render in iOS 10

### ISSUE THREAD

**Issue by jrames** [carekit-apple/CareKit#117] opened 2016-09-25 17:55 UTC
The below source worked successfully in iOS 9 for creating a document with a bar chart in it and displaying it in HTML format an email launched from the activity controller.  Note there are some minor differences here for Swift 3 compatibility, such as htmlContent rather than HTMLContent.

At this point, the document renders, but the barchart is invisible.  There is an area for it in the output, but it is blank.

Running the original code on an iOS 10 device (without Swift 3 modifications) yields the same results.

```
func connectViewController(_ connectViewController: OCKConnectViewController,
                           didSelectShareButtonFor contact: OCKContact,
                           presentationSourceView sourceView: UIView) {
  let document = carePlanData.generateDocumentWith(chart: insightChart)
  let activityViewController = UIActivityViewController(activityItems: [document.htmlContent],
                                                        applicationActivities: nil)

  present(activityViewController, animated: true, completion: nil)
}

```

Note that insightChart is an OCKBarChart ivar populated outside of this method.  I confirmed the object is there when this code runs.

I also tried creating a PDF document (saving to an ivar) and that yielded the same results with a blank bar chart in the PDF.

**Comment by djknowles** [comment] 2017-01-16 23:24
I have a similar issue. Interestingly this issue also occurs for ResearchKit charts when turned into OCKChart objects.

The code which is invoked to render the chart to HTML (which is required to produce HTML or PDF) is:

static NSString *imageTagFromImage (UIImage *image) {
    NSData *imageData = UIImagePNGRepresentation(image);
    NSString *format = @"<img style='vertical-align: middle;' alt=\"\" height='%@' width='%@' src='data:image/png;base64,%@' />\n";
    NSString *base64String = [imageData base64EncodedStringWithOptions:0];
    NSString *imageTag = [NSString stringWithFormat:format, @(image.size.height), @(image.size.width), base64String];
    return imageTag;
}

static NSString *imageTagFromView (UIView *view) {
    UIGraphicsBeginImageContextWithOptions(view.frame.size, YES, 2.0);
    [view.layer renderInContext:UIGraphicsGetCurrentContext()];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return imageTagFromImage(image);
}

Converted to Swift 3 (minor change to produce a full HTML page from a single chart):

    func imageTagFromImage(image: UIImage) -> String {
        let imageData = UIImagePNGRepresentation(image)
        let base64String = imageData?.base64EncodedString()
        let imageTag = "<html><body><img style='vertical-align: middle;' alt=\"\" height='\(image.size.height)' width='\(image.size.width)' src='data:image/png;base64,\(base64String!)' /></body></html>\n"
        return imageTag
    }
    
    func imageTagFromView(view: UIView) -> String {
        UIGraphicsBeginImageContextWithOptions(view.frame.size, true, 2.0);
        view.layer.render(in: UIGraphicsGetCurrentContext()!)
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return imageTagFromImage(image: image!)
    }

These functions work with a standard view with custom rendering however for the care kit chart the result is a blank image.

**Comment by djknowles** [comment] 2017-01-20 02:48
Finally worked out what was happening.

The following function in the file OCKDocument.m
was acting differently in iOS 9 and 10:

static NSString *imageTagFromView (UIView *view) {
    UIGraphicsBeginImageContextWithOptions(view.frame.size, YES, 2.0);
    [view.layer renderInContext:UIGraphicsGetCurrentContext()];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return imageTagFromImage(image);
}

In iOS 9 an extra update layoutSubviews was occurring during the first two lines of the lines of the function. This meant that the chart views were not being correctly laid out before rendering and rendered with the default frame which was (0, 0, 0, 0). This lead to the chart not displaying.

To fix this issue alter the above function to read as follows:

static NSString *imageTagFromView (UIView *view) {
    UIGraphicsBeginImageContextWithOptions(view.frame.size, YES, 2.0);
    **[view layoutIfNeeded];**
    [view.layer renderInContext:UIGraphicsGetCurrentContext()];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return imageTagFromImage(image);
}

The extra line [view layoutIfNeeded]; reintroduces the layout operation and the document displays the charts correctly.

**Comment by dukemike** [comment] 2017-02-03 16:37
@djknowles could you post a snippet around how you made the ORK charts available as OCK charts? I'm missing something fundamental when trying to create OCKChart subclasses.

**Comment by djknowles** [comment] 2017-02-07 22:58
Yes I had some trouble with this myself. In the end I created a view just to hold the chart and control the constraints. This I added to an OCKChart subclass which allowed it to be used in CareKit.

I have uploaded the code for the 3 charts: Line, Pie, Discrete.

[Charts.zip](https://github.com/carekit-apple/CareKit/files/759272/Charts.zip)

**Comment by dukemike** [comment] 2017-02-08 14:17
@djknowles Thanks! My problems were caused by not setting constraints and not coding the copy:withZone.

**Comment by umerkhan-apple** [comment] 2017-02-28 18:58
@dukemike @djknowles Is it okay to close this issue?

**Comment by dukemike** [comment] 2017-02-28 20:04
@umerkhan-apple yes, please do. Thanks!

**Closed** 2017-02-28 20:33 UTC
